Support for CORS
terraform-google-modules/terraform-google-cloud-storage pull request #128
Opened 2021-09-01 12:47 UTC by mkjmdski

I've noticed that simple_bucket is missing support for CORS so I decided to add it.

2021-09-03 09:31 UTC, mkjmdski commented
@morgante  could you review this too ?

2021-09-03 22:39 UTC, bharathkkb requested changes
Thanks for the PR @mkjmdski

2021-09-03 22:39 UTC, bharathkkb commented on modules/simple_bucket/variables.tf
> +  type = list(object({
we should use `any` and look up. This way users won't have to provide empty values for unused fields. [Example](https://github.com/terraform-google-modules/terraform-google-cloud-storage/blob/a0982c94f92df37d903af0a85e7ee5fe1e655d1e/variables.tf#L192)

2021-09-08 19:58 UTC, mkjmdski commented
hi @bharathkkb  I think this PR is ready to review again :)

2021-09-10 01:05 UTC, bharathkkb approved these changes

2021-09-10 01:06 UTC, merged