Adds cft.json to .gitignore
terraform-google-modules/terraform-google-cloud-storage pull request #173
Opened 2022-05-26 01:02 UTC by joaovitor

The cft.json created in this codelab is being commited by mistake in some prs.
This can generate leak and bad usage.

Adding `cft.json` go `.gitignore` can avoid versioning files that should not be versioned.

https://codelabs.developers.google.com/cft-onboarding?hl=en#3

2022-05-26 01:05 UTC, joaovitor commented
https://github.com/terraform-google-modules/terraform-google-cloud-storage/pull/172


https://github.com/terraform-google-modules/terraform-google-cloud-storage/pull/71/

2022-05-26 01:07 UTC, joaovitor commented
@kunalkg11 can you please review this PR?

2022-07-13 21:51 UTC, apeabody commented
/gcbrun

2022-07-13 21:57 UTC, apeabody requested changes
Hi @joaovitor - Thanks for the contribution!  Please see my question, thanks!

2022-07-13 21:57 UTC, apeabody commented on .gitignore
> -**/*.tfvars
Why is this being removed?

2022-11-11 20:20 UTC, bharathkkb commented
fixed by https://github.com/terraform-google-modules/terraform-google-cloud-storage/pull/199

2022-11-11 20:20 UTC, closed without merging