add Lifecycle conditions: MatchesPrefix, MatchesSuffix
terraform-google-modules/terraform-google-cloud-storage pull request #183
Opened 2022-08-12 12:58 UTC by elops-od

Support for new Lifecycle conditions: MatchesPrefix, MatchesSuffix

2022-09-16 07:03 UTC, idestis commented
Any progress here to merge required feature?

2022-09-22 10:12 UTC, idestis approved these changes

2022-09-26 13:52 UTC, idestis approved these changes

2022-09-26 14:56 UTC, bharathkkb requested changes
Thanks for the PR @elops-od 
Can we also add this to the main module? We will need to update the min provider version to 4.31 per https://github.com/hashicorp/terraform-provider-google/blob/main/CHANGELOG.md#4310-aug-1-2022

https://github.com/terraform-google-modules/terraform-google-cloud-storage/blob/80fa9e1fb247e9e86a1326157822687245661aa6/versions.tf#L23

https://github.com/terraform-google-modules/terraform-google-cloud-storage/blob/80fa9e1fb247e9e86a1326157822687245661aa6/modules/simple_bucket/versions.tf#L23

https://github.com/terraform-google-modules/terraform-google-cloud-storage/blob/80fa9e1fb247e9e86a1326157822687245661aa6/main.tf#L112-L131

2022-09-27 08:59 UTC, elops-od commented
> Thanks for the PR @elops-od Can we also add this to the main module? We will need to update the min provider version to 4.31 per https://github.com/hashicorp/terraform-provider-google/blob/main/CHANGELOG.md#4310-aug-1-2022
> 
> https://github.com/terraform-google-modules/terraform-google-cloud-storage/blob/80fa9e1fb247e9e86a1326157822687245661aa6/versions.tf#L23
> 
> https://github.com/terraform-google-modules/terraform-google-cloud-storage/blob/80fa9e1fb247e9e86a1326157822687245661aa6/modules/simple_bucket/versions.tf#L23
> 
> https://github.com/terraform-google-modules/terraform-google-cloud-storage/blob/80fa9e1fb247e9e86a1326157822687245661aa6/main.tf#L112-L131

hi
done

2022-09-28 07:49 UTC, idestis approved these changes

2022-09-29 06:39 UTC, elops-od commented
hi @bharathkkb 
could you pls review 
thank you

2022-09-29 23:07 UTC, bharathkkb reviewed
Could you add this to the main module too?
https://github.com/terraform-google-modules/terraform-google-cloud-storage/blob/80fa9e1fb247e9e86a1326157822687245661aa6/main.tf#L112-L131

2022-09-30 08:15 UTC, elops-od commented
> Could you add this to the main module too?
> 
> https://github.com/terraform-google-modules/terraform-google-cloud-storage/blob/80fa9e1fb247e9e86a1326157822687245661aa6/main.tf#L112-L131

hi
done

2022-10-07 08:12 UTC, idestis commented
@bharathkkb any progress with a review on this? The feature is really needed to use the module.

2022-10-19 08:08 UTC, muffl0n commented
Would love seeing this getting merged! Is there anything that is missing?

2022-11-08 12:08 UTC, elops-od commented
hi @bharathkkb @muffl0n 
any updates about merge ?

2022-11-14 08:57 UTC, elops-od commented
https://github.com/terraform-google-modules/terraform-google-cloud-storage/pull/183#issuecomment-1307455988
changed to 
```
        matches_prefix             = lookup(lifecycle_rule.value.condition, "matches_prefix", [])
        matches_suffix             = lookup(lifecycle_rule.value.condition, "matches_suffix", [])
```
but still get this error
@apeabody what I do wrong

2022-12-10 08:38 UTC, elops-od commented
@apeabody @muffl0n @bharathkkb 
hi guys 
any updates on this ?

2022-12-10 08:43 UTC, muffl0n commented
@elops-od, no need to tag me as I'm not a contributor to this PR. Just someone who would love to see this getting implemented.

2023-03-09 16:13 UTC, closed without merging