feat: adds support to autoclass
terraform-google-modules/terraform-google-cloud-storage pull request #265
Opened 2023-08-03 17:31 UTC by fernandoiury

This PR provides the autoclass feature for both  multiple_buckets and simple_bucket.

Closes https://github.com/terraform-google-modules/terraform-google-cloud-storage/issues/220

2023-08-03 18:05 UTC, apeabody commented
/gcbrun

2023-08-03 19:23 UTC, fernandoiury commented
@apeabody I just fixed lint. It's passing locally now. TIA

2023-08-03 22:04 UTC, apeabody commented
/gcbrun

2023-08-07 14:08 UTC, fernandoiury commented
@apeabody sorry I don't know the whole process. Do I have to do anything else or just wait for the reviewers for now? TIA

2023-08-07 15:04 UTC, apeabody commented
> @apeabody sorry I don't know the whole process. Do I have to do anything else or just wait for the reviewers for now? TIA

Hi @fernandoiury - Yes, typically wait for the reviewers, but I'll take a quick look at it now.

2023-08-07 15:16 UTC, apeabody requested changes
Thanks for the contribution @fernandoiury!  A few notes:

Please bump the minimum TPG version to the first which includes `autoclass`:
* https://github.com/terraform-google-modules/terraform-google-cloud-storage/blob/master/versions.tf#L23
* https://github.com/terraform-google-modules/terraform-google-cloud-storage/blob/master/modules/simple_bucket/versions.tf#L23

We should also exercise the new option in a test covered by the CI tests.  Basically just enable it for one of these examples:
* https://github.com/terraform-google-modules/terraform-google-cloud-storage/tree/master/examples

2023-08-07 15:16 UTC, apeabody commented on modules/simple_bucket/variables.tf
> +  default     = true
Unless autoclass is currently enabled by default, we should probably default this to `false` to maintain existing behavior (avoid breaking change).

```suggestion
  default     = false
```

2023-08-07 15:16 UTC, apeabody commented on variables.tf
> +  description = "Optional map of lowercase unprefixed name => boolean, defaults to false."
```suggestion
  description = "Optional map of lowercase unprefixed bucket name => boolean, defaults to false."
```

2023-08-07 16:03 UTC, fernandoiury commented
- Versions bumped
- Added autoclass = true to one of the examples
- fixed docs / updated metadata

2023-08-07 16:13 UTC, apeabody commented
/gcbrun

2023-08-07 16:27 UTC, apeabody approved these changes
Thanks for the contribution @fernandoiury - LGTM

As this requires a bump to minimum TPG (breaking change), I'll first release `4.0.1`.

2023-08-07 16:44 UTC, apeabody commented
/gcbrun

2023-08-07 16:58 UTC, merged